name: Deploy to Naver Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Naver Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /root/Cody-Now/
            sudo git pull origin main
            source venv/bin/activate
            pip3 install -r requirements.txt
            
            # static ë””ë ‰í† ë¦¬ ì„¤ì •
            sudo rm -rf staticfiles/*
            sudo mkdir -p staticfiles
            sudo chmod -R 777 staticfiles

            # production ì„¤ì •ìœ¼ë¡œ collectstatic ì‹¤í–‰
            python3 manage.py collectstatic --noinput --settings=config.settings.production
            python3 manage.py migrate --settings=config.settings.production
            
            # ì„œë¹„ìŠ¤ ì¬ì‹œì‘
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx

      - name: Send Slack notification (Success)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "ğŸš€ *Deploy ì„±ê³µ!* \nBranch: ${{ github.ref }} \nCommit: ${{ github.sha }} \nğŸŸ¢ ì„œë¹„ìŠ¤ê°€ ì •ìƒì ìœ¼ë¡œ ë°°í¬ë˜ì—ˆìŠµë‹ˆë‹¤!"
          SLACK_COLOR: "#36a64f"

      - name: Send Slack notification (Failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "âŒ *Deploy ì‹¤íŒ¨!* \nBranch: ${{ github.ref }} \nCommit: ${{ github.sha }} \nğŸ”´ ë°°í¬ ì¤‘ ì˜¤ë¥˜ê°€ ë°œìƒí–ˆìŠµë‹ˆë‹¤. ë¡œê·¸ë¥¼ í™•ì¸í•˜ì„¸ìš”."
          SLACK_COLOR: "#ff0000"